export const VICTORIAN_SCHOOLS: string[] = [
  'Al Siraat College',
  'Al-Taqwa College',
  'Albert Park College',
  'Alice Miller School',
  'Alkira Secondary College',
  'Alphington Grammar School',
  'Altona College',
  'Apollo Bay P-12 College',
  'Ashwood High School',
  'Auburn High School',
  'Avila College',
  'Bacchus Marsh Grammar',
  'Ballarat Clarendon College',
  'Ballarat Grammar',
  'Balwyn High School',
  'Bannockburn P-12 College',
  'Beaconhills College',
  'Beaumaris Secondary College',
  'Beechworth Secondary College',
  'Belmont High School',
  'Bentleigh Secondary College',
  'Berwick Grammar School',
  'Beth Rivkah Ladies College',
  'Bialik College',
  'Billanook College',
  'Birchip P-12 School',
  'Blackburn High School',
  'Box Hill High School',
  'Braemar College',
  'Brauer College',
  'Braybrook College',
  'Brentwood Secondary College',
  'Brighton Grammar School',
  'Brighton Secondary College',
  'Brunswick Secondary College',
  'Buckley Park College',
  'Camberwell Girls Grammar School',
  'Camberwell Grammar School',
  'Camberwell High School',
  'Canterbury Girls Secondary College',
  'Carey Baptist Grammar School',
  'Carwatha College P-12',
  'Catholic Ladies College',
  'Caulfield Grammar School',
  'Charlton College',
  'Cheltenham Secondary College',
  'Coburg High School',
  'Cornish College',
  'Corryong College',
  'Darul Ulum College of Victoria',
  'Daylesford Secondary College',
  'Doncaster Secondary College',
  'Donvale Christian College',
  'Dromana Secondary College',
  'East Doncaster Secondary College',
  'East Loddon P-12 College',
  'Edenbrook Secondary College',
  'Elisabeth Murdoch College',
  'Eltham College',
  'Eltham High School',
  'Fairhills High School',
  'Fintona Girls\' School',
  'Firbank Grammar School',
  'Fitzroy High School',
  'Footscray High School',
  'Forest Hill College',
  'Fountain Gate Secondary College',
  'Frankston High School',
  'Geelong Grammar School',
  'Geelong High School',
  'Genazzano FCJ College',
  'Gippsland Grammar',
  'Girton Grammar School',
  'Gladstone Park Secondary College',
  'Glen Eira College',
  'Glen Waverley Secondary College',
  'Good News Lutheran College',
  'Goulburn Valley Grammar School',
  'Haileybury',
  'Harkaway Hills College',
  'Heathdale Christian College',
  'Heatherton Christian College',
  'Highvale Secondary College',
  'Horsham College',
  'Hume Anglican Grammar',
  'Huntingtower School',
  'Islamic College of Melbourne',
  'Ivanhoe Girls\' Grammar School',
  'Ivanhoe Grammar School',
  'John Monash Science School',
  'Kambrya College',
  'Kardinia International College',
  'Keilor Downs College',
  'Kew High School',
  'Kilbreda College',
  'Kilvington Grammar School',
  'Kingswood College',
  'Koonung Secondary College',
  'Korowa Anglican Girls\' School',
  'Lauriston Girls\' School',
  'Leibler Yavneh College',
  'Leongatha Secondary College',
  'Lighthouse Christian College',
  'Loreto Mandeville Hall',
  'Lowther Hall Anglican Grammar School',
  'Luther College',
  'Mac.Robertson Girls\' High School',
  'Maffra Secondary College',
  'Mansfield Secondary College',
  'Maranatha Christian School',
  'Matthew Flinders Girls Secondary College',
  'Mazenod College',
  'McKinnon Secondary College',
  'Melbourne Girls Grammar School',
  'Melbourne Girls\' College',
  'Melbourne Grammar School',
  'Melbourne High School',
  'Mentone Girls\' Grammar School',
  'Mentone Girls\' Secondary College',
  'Mentone Grammar School',
  'Methodist Ladies\' College',
  'Montmorency Secondary College',
  'Mordialloc College',
  'Mount Alexander College',
  'Mount Scopus Memorial College',
  'Mount Waverley Secondary College',
  'Mullauna College',
  'Northcote High School',
  'Northside Christian College',
  'Nossal High School',
  'Nunawading Christian College',
  'Oberon High School',
  'OneSchool Global Vic',
  'Orbost Secondary College',
  'Our Lady of Mercy College',
  'Our Lady of Sion College',
  'Ouyen P-12 College',
  'Overnewton Anglican Community College',
  'Oxley Christian College',
  'Parkdale Secondary College',
  'Penleigh and Essendon Grammar School',
  'Peninsula Grammar',
  'Prahran High School',
  'Presbyterian Ladies\' College',
  'Preston High School',
  'Princes Hill Secondary College',
  'Richmond High School',
  'Ringwood Secondary College',
  'Ruyton Girls\' School',
  'Sacre Coeur',
  'Sandringham College',
  'Scotch College',
  'Shelford Girls\' Grammar',
  'Siena College',
  'Sirius College',
  'South Oakleigh College',
  'Southern Cross Grammar',
  'St Albans Secondary College',
  'St Andrews Christian College',
  'St Catherine\'s School',
  'St Helena Secondary College',
  'St Kevin\'s College',
  'St Leonard\'s College',
  'St Margaret\'s School',
  'St Mary\'s Coptic Orthodox College',
  'St Michael\'s Grammar School',
  'St Paul\'s Anglican Grammar School',
  'Star of the Sea College',
  'Strathcona Baptist Girls\' Grammar School',
  'Strathmore Secondary College',
  'Surf Coast Secondary College',
  'Suzanne Cory High School',
  'Swinburne Senior Secondary College',
  'Taylors Lakes Secondary College',
  'Templestowe College',
  'The Geelong College',
  'The King David School',
  'The Knox School',
  'Thornbury High School',
  'Tintern Grammar',
  'Toorak College',
  'Trinity Grammar School',
  'University High School',
  'Upper Yarra Secondary College',
  'Vermont Secondary College',
  'Victory Christian College',
  'Victorian College of the Arts Secondary School',
  'Viewbank College',
  'Waverley Christian College',
  'Wedderburn College',
  'Wellington Secondary College',
  'Werribee Secondary College',
  'Wesley College',
  'Westbourne Grammar School',
  'Williamstown High School',
  'Woodmans Hill Secondary College',
  'Wycheproof P-12 College',
  'Xavier College',
  'Yarra Valley Grammar School',
  'Yesodei HaTorah College',
  'Yeshivah College',
];
